[packaging]
package_name = "azure-mgmt-quota"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Quota Management"
package_doc_id = ""
is_stable = false
is_arm = true
need_msrestazure = false
need_azuremgmtcore = true
title = "QuotaMgmtClient"
