[packaging]
package_name = "azure-mgmt-recoveryservicesbackup"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Recovery Services Backup Management"
package_doc_id = ""
is_stable = false
is_arm = true
