[packaging]
package_name = "azure-cognitiveservices-search-customsearch"
package_nspkg = "azure-cognitiveservices-search-nspkg"
package_pprint_name = "Cognitive Services Custom Search"
package_doc_id = "cognitive-services"
is_stable = false
is_arm = false
need_msrestazure = false
auto_update = false
