[packaging]
package_name = "azure-mgmt-iothubprovisioningservices"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "IoT Hub Provisioning Services"
package_doc_id = "iot"
is_stable = false
is_arm = true
