[packaging]
package_name = "azure-mgmt-storage"
package_pprint_name = "Storage Management"
package_doc_id = "?view=azure-python-preview"
is_stable = true
need_msrestazure = false
need_azurecore = true
