[build-system]
requires = ["setuptools>=77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "azure-identity"
authors = [
    {name = "Microsoft Corporation", email = "azpysdkhelp@microsoft.com"},
]
description = "Microsoft Azure Identity Library for Python"
keywords = ["azure", "azure sdk"]
requires-python = ">=3.9"
license = "MIT"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "azure-core>=1.31.0",
    "cryptography>=2.5",
    "msal>=1.30.0",
    "msal-extensions>=1.2.0",
    "typing-extensions>=4.0.0",
]
dynamic = ["version", "readme"]

[project.urls]
repository = "https://github.com/Azure/azure-sdk-for-python"

[tool.setuptools.dynamic]
version = {attr = "azure.identity._version.VERSION"}
readme = {file = ["README.md", "CHANGELOG.md"], content-type = "text/markdown"}

[tool.setuptools.packages.find]
exclude = ["tests*", "samples*", "azure"]

[tool.setuptools.package-data]
pytyped = ["py.typed"]

[tool.azure-sdk-build]
pyright = false
verifytypes = true
black = true
