[packaging]
package_name = "azure-mgmt-recoveryservicessiterecovery"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Recovery Services Site Recovery Management"
package_doc_id = ""
is_stable = false
is_arm = true
