[packaging]
package_name = "azure-mgmt-hybridcontainerservice"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Hybridcontainerservice Management"
package_doc_id = ""
is_stable = true
is_arm = true
need_msrestazure = false
need_azuremgmtcore = true
sample_link = ""
title = "HybridContainerServiceMgmtClient"
