[packaging]
package_name = "azure-cognitiveservices-vision-customvision"
package_pprint_name = "Custom Vision"
package_doc_id = "cognitive-services"
is_stable = false
is_arm = false
need_msrestazure = false
auto_update = false
