[packaging]
package_name = "azure-cognitiveservices-search-imagesearch"
package_nspkg = "azure-cognitiveservices-search-nspkg"
package_pprint_name = "Cognitive Services Image Search"
package_doc_id = "cognitive-services"
is_stable = true
is_arm = false
auto_update = false
