[packaging]
package_name = "azure-mgmt-eventhub"
package_pprint_name = "EventHub Management"
package_doc_id = "event-hub?view=azure-python-preview"
is_stable = true
need_msrestazure = false
need_azuremgmtcore = true
