[packaging]
package_name = "azure-mgmt-edgegateway"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Data Box Edge / Data Box Gateway"
package_doc_id = ""
is_stable = false
is_arm = true
need_msrestazure = true
need_azuremgmtcore = false
