[packaging]
package_name = "azure-mgmt-apimanagement"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "API Management"
package_doc_id = ""
is_stable = true
is_arm = true
sample_link = ""
title = "ApiManagementClient"
