[packaging]
package_name = "azure-mgmt-azurelargeinstance"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Azurelargeinstance Management"
package_doc_id = ""
is_stable = false
is_arm = true
need_msrestazure = false
need_azuremgmtcore = true
sample_link = ""
exclude_folders = ""
title = "LargeInstanceMgmtClient"
auto_update = false
