[packaging]
package_name = "azure-ai-textanalytics"
package_nspkg = "azure-ai-nspkg"
package_pprint_name = "Azure Text Analytics"
package_doc_id = ""
is_stable = false
is_arm = false
need_msrestazure = false
