[tool.azure-sdk-build]
mypy = false
pyright = false
type_check_samples = false
verifytypes = false
pylint = false
sphinx = false
verifysdist = false
verifywhl = false
sdist = false
breaking = false
# these can be any number of suppressions. note that * present means that ALL warnings will be suppressed for this package
suppressed_skip_warnings = ["*"]

[build-system]
requires = ["setuptools", "wheel", "cibuildwheel"]

[tool.cibuildwheel]
build = ["cp38*", "pp38*", "pp39*", "pp310*"]
test-requires = "pytest"
test-command = "pytest {project}/tests"
test-skip = "*-macosx_arm64"

[tool.cibuildwheel.linux]
archs = "x86_64 aarch64"

[tool.cibuildwheel.macos]
archs = "x86_64 arm64"
environment = "CFLAGS='-Wno-implicit-function-declaration'"

[tool.cibuildwheel.windows]
archs = "AMD64"
