[packaging]
package_name = "azure-synapse-managedprivateendpoints"
package_nspkg = "azure-synapse-nspkg"
package_pprint_name = "Synapse Vnet"
package_doc_id = ""
is_stable = false
is_arm = false
need_msrestazure = false
need_azurecore = true