[packaging]
package_name = "azure-mgmt-agrifood"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Agrifood Management"
package_doc_id = ""
is_stable = false
is_arm = true
need_msrestazure = false
need_azuremgmtcore = true
