[tool.azure-sdk-build]
breaking = false
pyright = false
mypy = false

[packaging]
package_name = "azure-mgmt-cognitiveservices"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Cognitive Services Management"
package_doc_id = "cognitive-services"
is_stable = true
is_arm = true
sample_link = ""
title = "CognitiveServicesManagementClient"
