[packaging]
package_name = "azure-mgmt-storageimportexport"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Storage Import Export Management"
package_doc_id = ""
is_stable = false
is_arm = true
