[packaging]
package_name = "azure-mgmt-baremetalinfrastructure"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Bare Metal Infrastructure Management"
package_doc_id = ""
is_stable = false
is_arm = true
