[packaging]
package_name = "azure-mgmt-resourceconnector"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Resource Connector Management"
package_doc_id = ""
is_stable = false
is_arm = true
title = "ResourceConnectorMgmtClient"
