[packaging]
package_name = "azure-mgmt-notificationhubs"
package_pprint_name = "Notification Hubs Management"
package_doc_id = "notification-hubs"
is_stable = true
sample_link = ""
title = "NotificationHubsManagementClient"
