[packaging]
package_name = "azure-mgmt-dnc"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "MyService Management"
package_doc_id = ""
is_stable = false
is_arm = true
need_msrestazure = false
need_azuremgmtcore = true
