[packaging]
package_name = "azure-mgmt-neonpostgres"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Neonpostgres Management"
package_doc_id = ""
is_stable = true
is_arm = true
need_msrestazure = false
need_azuremgmtcore = true
sample_link = ""
exclude_folders = ""
title = "NeonPostgresMgmtClient"
