[packaging]
package_name = "azure-cognitiveservices-knowledge-qnamaker"
package_nspkg = "azure-cognitiveservices-knowledge-nspkg"
package_pprint_name = "QnA Maker"
package_doc_id = "cognitive-services"
is_stable = false
is_arm = false
need_msrestazure = false
auto_update = false
