[packaging]
package_name = "azure-mgmt-connectedcache"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Connectedcache Management"
package_doc_id = ""
is_stable = false
is_arm = true
need_msrestazure = false
need_azuremgmtcore = true
sample_link = ""
exclude_folders = ""
title = "ConnectedCacheMgmtClient"
