[packaging]
package_name = "azure-mgmt-kubernetesconfiguration-extensiontypes"
package_nspkg = "azure-mgmt-kubernetesconfiguration-nspkg"
package_pprint_name = "Kubernetesconfiguration-extensiontypes Management"
package_doc_id = ""
is_stable = false
is_arm = true
need_msrestazure = false
need_azuremgmtcore = true
sample_link = ""
exclude_folders = ""
title = "KubernetesConfigurationExtensionTypesMgmtClient"
