[packaging]
package_name = "azure-mgmt-resource-deployments"
package_nspkg = "azure-mgmt-resource-nspkg"
package_pprint_name = "Resource Deployments Management"
package_doc_id = ""
is_stable = false
is_arm = true
need_msrestazure = false
need_azuremgmtcore = true
sample_link = ""
exclude_folders = ""
title = "DeploymentsMgmtClient"
