[packaging]
package_name = "azure-cognitiveservices-search-videosearch"
package_nspkg = "azure-cognitiveservices-search-nspkg"
package_pprint_name = "Cognitive Services Video Search"
package_doc_id = "cognitive-services"
is_stable = true
is_arm = false
auto_update = false
