[packaging]
package_name = "azure-mgmt-network"
package_pprint_name = "Network Management"
package_doc_id = "network?view=azure-python-preview"
is_stable = true
is_arm = true
need_msrestazure = false
need_azuremgmtcore = true
sample_link = ""
title = "NetworkManagementClient"
