[packaging]
package_name = "azure-mgmt-machinelearningcompute"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Machine Learning Compute Management"
package_doc_id = ""
is_stable = false
is_arm = true
