[packaging]
package_name = "azure-mgmt-desktopvirtualization"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Desktop Virtualization Management"
package_doc_id = ""
is_stable = false
is_arm = true
