[tool.azure-sdk-build]
breaking = false
mypy = false
pyright = false
type_check_samples = false
verifytypes = false

[packaging]
package_name = "azure-mgmt-computefleet"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Computefleet Management"
package_doc_id = ""
is_stable = false
is_arm = true
need_msrestazure = false
need_azuremgmtcore = true
sample_link = ""
exclude_folders = ""
title = "ComputeFleetMgmtClient"
