[packaging]
package_name = "azure-mgmt-vmwarecloudsimple"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "VMWare Cloud Simple Management"
package_doc_id = ""
is_stable = false
is_arm = true
