[project]
name = "azure-sdk-python-mcp"
version = "0.1.2"
description = "MCP server for Azure SDK for Python"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "azure-core>=1.34.0",
    "mcp[cli]>=1.9.2",
    "mypy>=1.16.0",
    "pip>=25.1.1",
    "pygithub>=2.6.1",
    "pylint>=3.3.7",
    "tox>=4.26.0",
    "httpx>=0.24.0",
    "tox-uv>=1.25.0",
]

[project.scripts]
azure-sdk-python-mcp = "main:main"

[[tool.uv.index]]
name = "azure-sdk-python-mcp"
url = "https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-python/pypi/simple/"
publish-url = "https://pkgs.dev.azure.com/azure-sdk/public/_artifacts/feed/azure-sdk-for-python/pypi/upload/"
