[packaging]
package_name = "azure-cognitiveservices-language-textanalytics"
package_nspkg = "azure-cognitiveservices-language-nspkg"
package_pprint_name = "Cognitive Services Text Analytics"
package_doc_id = "cognitive-services"
is_stable = false
is_arm = false
need_msrestazure = false
auto_update = false
