[packaging]
package_name = "azure-mgmt-machinelearningservices"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Machine Learning Services Management"
package_doc_id = ""
is_stable = false
is_arm = true
