# Variables: 
#  'build_targeting_string' comma separated glob strings selecting the packages that should be built. EG: "azure-keyvault,azure-mgmt-batch" or "azure-*"

parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ format('Test_{0}', parameters.name ) }}
  dependsOn:
  - 'Build_Target_Packages'
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      Python_27:
        python.version: '2.7'
      Python_34:
        python.version: '3.4'
      Python_35:
        python.version: '3.5'
      Python_36:
        python.version: '3.6'
      Python_37:
        python.version: '3.7'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'

  - powershell: |
     $inputFilterSet="$(build_targeting_string)"
     
     if ($inputFilterSet -eq "")
     {
        $inputFilterSet = "azure-*"
     }
     
     foreach($inputFilter in $inputFilterSet.split(","))
     {
        python scripts/dev_setup.py -g $inputFilter
     }
    displayName: 'Test Setup'

  - powershell: |
     $inputFilterSet="$(build_targeting_string)"
     
     if ($inputFilterSet -eq "")
     {
        $inputFilterSet = "azure-*"
     }
     
     foreach($inputFilter in $inputFilterSet.split(","))
     {
        $folderCombination = (gci -Directory -Name -Filter "$inputFilter"  | %{ "$(Build.SourcesDirectory)/$_/" }) -join " "
        pytest $folderCombination
     }
    displayName: 'Run Test Subset'

  - script: |
     python ./setup.py check -r -s
    displayName: 'Check Setup.py Files'