[packaging]
package_name = "azure-cognitiveservices-vision-contentmoderator"
package_nspkg = "azure-cognitiveservices-vision-nspkg"
package_pprint_name = "Cognitive Services Content Moderator"
package_doc_id = "cognitive-services"
is_stable = true
is_arm = false
need_msrestazure = false
auto_update = false